//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobify.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ResumeFile
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public string Path { get; set; }
        public Nullable<int> ResumeId { get; set; }
        public HttpPostedFileBase PdfFile { get; set; }
        public virtual Resume Resume { get; set; }
    }
}
